### PR TITLE
Final Prototype without firebase key authentication. This needs to be…

### PR DESCRIPTION
**Pull request by rohan5046**
… resolved and I will update this in the next version due to authentication issues with the private key

### CODE REVIEW

**Review by NiyamC — APPROVED** [review]
Will try sort out database authentication today, if not we will just have to resort to using screenshots for output.

**Comment by sxb1845** [comment]
Before you merge this, making a pull request for this branch to make the test not fail

**Review by sxb1845 — CHANGES_REQUESTED** [review]
We should see #20 before merging this

**Review by sxb1845 — APPROVED** [review]
Looks good

**Pull request merged**
